### ISSUE TITLE
Unclear How To Disable HTML Escaping?

### ISSUE THREAD

**Issue by derks** [wbond/pybars3#25]
I see in the code where HTML special characters are escaped (or not escaped) via the `prepare()` function... however it is unclear if it is possible to disable HTML escaping at the Compiler level?

Something like:

``` python
compiler = Compiler()
source = u"This is not **HTML**, it is `MarkDown`"
template = compiler.compile(source, escape_html=False)
```

I use plain text templates, MarkDown, and other non-standard files as template sources....  and do not want it treated as HTML at all.  Possible?

**Comment by derks** [comment]
Currently, the only way I see possible to disable HTML escaping at a high level is to monkey patch the `prepare` function, which is obviously not ideal:

```python
# monkey patch so we don't escape special characters for HTML (not clear how else to do this)
import pybars._compiler

original_prepare = pybars._compiler.prepare
def my_prepare(value, escape):
    return original_prepare(value, False)

pybars._compiler.prepare = my_prepare

from pybars import Compiler
compiler = Compiler()
source = u"This is not **HTML**, it is `MarkDown`"
template = compiler.compile(source)
```


Any help, or patch suggestions would be much appreciated.

**Comment by dagnelies** [comment]
...you can use triple mustaches if you want unescaped content

**Comment by derks** [comment]
@dagnelies The templates I'm using, and output I'm generating are not HTML... therefore, having to managing escaping HTML on every template doesn't make sense.  Also, I believe triple escaping would also escape all other uses (such as handlebars variables, etc)... no?

**Comment by dagnelies** [comment]
Citing handlebars.js:

> Handlebars HTML-escapes values returned by a `{{expression}}`. If you don't want Handlebars to escape a value, use the "triple-stash", `{{{expression}}}`.

Note that escaped characters should be recognized by a correct Markdown implementation anyway and will not result in doubly escaped. Citing their doc:

> If you use an ampersand as part of an HTML entity, it remains unchanged; otherwise it will be translated into &amp;.

**Comment by maxkoryukov** [comment]
@derks may be it makes sense to replace `{{` to `{{{` before compiling?

Looks like you want to use Handlebars, but with **custom** rules. But finally, if template doesn't follow Handlebars rules, it can not be compiled with Handlebars **correct (with expected result)** in common case

**Comment by maxkoryukov** [comment]
@derks , another one solution: escaping. Original Handlebars has support for two things:

1. inline escape `\{{ this stuff will be rendered as is }  }} } `
  Link to documentation: [tinz](http://handlebarsjs.com/expressions.html#escaping)
2. raw blocks (with helpers): `{{{{rawHelper}}}} this content will be treated literally *asdf* _xx_ {{{{/rawHelper}}}}`
  Link to documentation: [asd](http://handlebarsjs.com/block_helpers.html#raw-blocks)

Here a link to [PR](wycats/handlebars.js#730)

I am not sure, whether the pybars implements this stuff

**Comment by thomasst** [comment]
We did it like this: https://github.com/closeio/pybars/commit/f7b717fd6f533a7a88c5b7e09a7f55e35332f83a

Feel free to incorporate the code (it probably won't merge cleanly into the current pybars3).

**Comment by isaacdd** [comment]
Raw blocks is out with 0.9.4. Closing this issue.

**Comment by jace** [comment]
I have arrived at the same problem as @derks had, but with an additional requirement: escaping Markdown markup characters. My processing flow is:

`.hbs` -> pybars3 -> `.md` -> Markdown -> `.html`

If a template variable has Markdown markup characters in it, neither `{{ var }}` nor `{{{ var }}}` will escape them. I can pre-escape all variables before passing them to pybars3, but this will mean `{{{ var }}}` cannot be used to insert unescaped content.

The ideal solution is to allow customisation of the `escape` implementation in the compiler's settings.
