### ISSUE TITLE
Raw blocks support

### ISSUE THREAD

**Issue by maxkoryukov** [wbond/pybars3#36]
Raw blocks `{{{{raw-helper}}}} raw content {{bar}} {{{{/raw-helper}}}}` are not implemented

Documentation: http://handlebarsjs.com/block_helpers.html#raw-blocks

**Comment by maxkoryukov** [comment]
PR for this could close #24  and #25

**Comment by isaacdd** [comment]
Support is available in 0.9.4

**Comment by orgads** [comment]
The link is broken. This is the new location: https://handlebarsjs.com/guide/block-helpers.html#raw-blocks
