### ISSUE TITLE
Travis CI Config for Python 3

### ISSUE THREAD

**Issue by wbond** [wbond/pybars3#39]
The whole point of this library versus pybars is to support Python 3. The Travis CI config should probably run this on at least Python 3.3 and 2.7 because of that.

**Comment by maxkoryukov** [comment]
Absolutely... I tried to build **pybars3** with different python versions, and there are several different issues. Here is a link to my build: https://travis-ci.org/maxkoryukov/pybars3/builds/184107757

#### flake8

```
./pybars/_compiler.py:185:25: F821 undefined name 'unicode'
./pybars/_compiler.py:271:16: F821 undefined name 'unicode'
2     F821 undefined name 'unicode'
```

#### tests / coverage

The code doesn't pass all tests, in most cases I got:

```
AttributeError: 'PybarsError' object has no attribute 'message'
```

**Comment by maxkoryukov** [comment]
FYI: I have a [branch](https://github.com/maxkoryukov/pybars3/tree/travis-py-3) for this issue, I think, I could fix this on this week

**Comment by wbond** [comment]
Rather than `e.message` you should be casting the error to str.

**Comment by maxkoryukov** [comment]
it is your test code ;))

anyway: `e.message` => `str(e)` **DONE**

* **python 2.6** - fucked up.. users with python 2.6 should upgrade their soft
* **python 3.2** - doesn't know what to do with `u'some string'`. I think, we could drop this version too;)
