### ISSUE TITLE
../ does not work

### ISSUE THREAD

**Issue by adambom** [wbond/pybars3#5]
Putting ../ within any block helper does not give you a reference to the parent scope.

FYI: for anyone else having this problem, the workaround is to use a helper called include_parent:

```python
def include_parent(this, options, *args, **kwargs):
    this.context['parent'] = this.parent
    return options['fn'](this)
```

Put it in your templates like so:

```handlebars
{{#each foo}}
    {{#include_parent}}
    {{parent.bar}}
{{/each}}
````

**Comment by wbond** [comment]
I believe this should be working. There are quite a number of tests that use the `../` syntax. As of the summer 2014, support for `@_parent` was also added.

**Comment by wbond** [comment]
Feel free to reopen or create a new issue if you can provide an example that fails.
