### ISSUE TITLE
Source tarball doesnt include LICENSE

### ISSUE THREAD

**Issue by jayvdb** [wbond/pybars3#52]
At least the LICENSE should be in the source tarball.

The readme.md & changelog.md would be good additions.

And the tests would also be useful for running to check rpm packages were build/installed correctly.

**Comment by jayvdb** [comment]
c.f. https://build.opensuse.org/request/show/666073

**Comment by isaacdd** [comment]
Fixed in https://github.com/wbond/pybars3/pull/66
