### ISSUE TITLE
Whitespace control

### ISSUE THREAD

**Issue by JGoutin** [wbond/pybars3#63]
I have to render some templates that use whitespace control. I see that this is a known missing feature in the readme. Is there plan to support it ?

I fixed the template before it them using regex like:
```python
re.sub(r'\s*{{~', '{{', template)
```
This solution may eventually also be used in pybars3.

**Comment by wbond** [comment]
If someone writes up an implementation with tests, myself or another contributor will look it over.

That said, this project is mostly a "scratch your own itch and add a feature you need" kind of project. I rarely use the library, and don't have a need for this feature, and don't have much time for open source, so I know I won't be implementing it.

**Comment by JGoutin** [comment]
OK, I pushed a #64 with a basic support.
