### ISSUE TITLE
check existance at specific index in array

### ISSUE THREAD

**Issue by dazoot** [wbond/pybars3#67]
When i check the existence of an array item at specific index, i get an IndexError: list index out of range.

My template:
```
{{#if latestProjectsFreeForView.3.projectName}}
{{/if}}
```

`latestProjectsFreeForView` has just 2 items.

In javascript version it works.

**Comment by joseleperez** [comment]
Is there an estimate on when this will be merged to master?

**Comment by wbond** [comment]
No, everyone who works on this repo does so in their free time. Feel free to fork and rename if you are interested in maintaining the project.
