### ISSUE TITLE
Support Helper in Html Template?

### ISSUE THREAD

**Issue by jl-DaDar** [wbond/pybars3#75]
Is there a way to use javascript helper or  python helper in html template?
I tried to add js helper in the html because handlebarjs does support it. but It does not work with pybar3. 

I got this error

`  File "/usr/local/lib/python3.8/site-packages/pybars/_compiler.py", line 448, in _helperMissing
    raise PybarsError(u"Could not find property %s" % (name,))
pybars._compiler.PybarsError: Could not find property format`

I know pybar supports adding helper in the code and then compile, but that is not very useful. It makes template inflexible and unmanageable. 

I was thinking if there is a way to add helper (python or js) inside the html instead.

thanks.

**Comment by wbond** [comment]
I don't foresee working on this. Putting eval'ed Python into a template sounds like a bad idea from a security perspective.

For Handlebars and JS, there is already a client side environment, so there isn't the same sort of security to be concerned about.

**Comment by jl-DaDar** [comment]
Hi wbond, 

thanks for the response. I am not sure what you meant by "For Handlebars and JS, there is already a client side environment,"

We want to allow user to manage template without changing server code. So theat they can just submit templates into the database and compile at the server runtime when an email needs to be sent. Do you know any workaround to my issue?
