### ISSUE TITLE
Rename the fork?

### ISSUE THREAD

**Issue by webmaven** [wbond/pybars3#9]
If your version of pybars supports the partial syntax ```{{> partialName}}``` I suggest renaming based on a [beard name](http://zouchmagazine.com/the-hierarchy-of-beard-moustache-charts/), such as Ducktail.

I'll create a logo for the forked project if you do.

**Comment by wbond** [comment]
It has been renamed to pybars3 (I know, boring), and posted on PyPi.

I think a new name may be in order if I ever get around to a clean re-implementation, but I just wanted to make it easy for people to grab from PyPi.
